name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Build
        run: |
          cd C:\
          git clone --depth=1 https://github.com/CzBiX/qb-web.git
          cd qb-web
          yarn install
          yarn run build
      - name: Package Directories
        run: |
          7z a qb-web_latest.7z C:\qb-web\public
      - uses: actions/upload-artifact@v3
        with:
          name: qb-web_latest
          path: qb-web_latest.7z
